import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import { SessionProvider } from "next-auth/react";
import { Toaster as Toast } from "react-hot-toast";
export const metadata: Metadata = {
  title: "Attendance system",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <SessionProvider>
        <body>
          <Toast position="top-right"></Toast>
          {children}
          <Toaster/>
        </body>
      </SessionProvider>
    </html>
  );
}
